// import "./modules/013script.js";
// import "./modules/018script.js";
// import "./modules/023script.js";
// import "./modules/031script.js";
// import "./modules/object.js";
// import "./modules/arr.js";
// import "./modules/oop.js";
// import "./modules/dynamTipizacia.js";
// import "./modules/zamikanie_leksiceskoeOkrugenie.js";
import "./modules/event.js";
